### PR TITLE
ISSUE #1111 - Fix the override all flag when you go back from editing a group

### LINKED ISSUE #1111: Groups -  after editing a group the override all flag is being reset
### Description
After editing a group the override all flag is being reset.

### Steps to replicate
- Open groups
- Check override all in the component windows dropdown, top right
- Edit a group
- Go back, if you check the dropdown

### Pictures/ Gifs of the error
override all

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #1111 

#### Description
 Fixes the override all flag when you go back from editing a group

#### Test cases
Set override all , edit a group, comeback. Should stay still with override all.

### CODE REVIEW

File: frontend/components/groups/js/groups.component.ts [hunk 1]
```diff
@@ -54,6 +54,7 @@ class GroupsController implements ng.IController {
 	private savedGroupData: any;
 	private customIcons: any;
 	private lastColorOverride: any;
+	private lastColorOverrideAll: any;
```
Comment (carmenfan) [inline frontend/components/groups/js/groups.component.ts]: I don't think this is the best approach.

There's 2 problems, 
- another class scope variable which is not desirable
- when you call colorOverrideAllGroups(), it runs the computation again for all the groups (even though we know for a fact that n-1 groups are already overridden

I think it's better if you have a flag passed into `GroupService.removeColorOverride()`, telling it to ignore resetting overrideAll, which wouuld only set to true if we are removing override because we entered the edit page

Let me know what you think! 😄
