### PR TITLE
ISSUE #5292 - fixed user removed from teamspace crashing the tickets list

### LINKED ISSUE #5292: Opening tickets list crashes the app
#### Description
App crashes sometimes when opening tickets list

#### Steps to reproduce
- Remove a user from a teamspace
- Open up the tickets list for a model that uses this recently removed user as an assignee

#### Current behaviour
The app whitescreens

#### Expected behaviour
The app does not crash and correctly shows that the user is assigned but is invalid

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #5292

#### Description
Users that were removed from the teamspace but still assigned to a ticket was causing a crash when opening the tickets list

#### Test cases
Try to open the tickets list with tickets that are assigned to users who have been removed from this teamspace

### CODE REVIEW

File: frontend/src/v5/ui/controls/assigneesSelect/assigneesSelect.component.tsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ export const AssigneesSelect = ({
 	const teamspaceJobsAndUsers = UsersHooksSelectors.selectJobsAndUsersByIds();
 	const valueToJobOrUser = (val: string) => teamspaceJobsAndUsers[val];
 	const allJobsAndUsersToDisplay = [
-		...validValues.map(valueToJobOrUser),
+		...validValues.map((v) => valueToJobOrUser || ({ invalidItemName: v })),
```
Comment (Amantini1997) [inline frontend/src/v5/ui/controls/assigneesSelect/assigneesSelect.component.tsx:65]: This `||` shouldn't be here: the "invalidItemName" should only be used if the value is invalid, so what's on the line below.
Also, you are no longer invoking the `valueToJobOrUser`

File: frontend/src/v5/ui/controls/assigneesSelect/assignees.helpers.ts [hunk 2]
```diff
@@ -50,5 +50,5 @@ export const groupJobsAndUsers = (items) => {
 		if (item?._id) return 'jobs';
 		return 'notFound';
 	});
-	return { users, jobs, notFound } as { users: IUser[], jobs: IJob[], notFound: { notFoundName: string }[] };
+	return { users, jobs, notFound } as { users: IUser[], jobs: IJob[], notFound: { invalidItemName: string }[] };
```
Comment (Amantini1997) [inline frontend/src/v5/ui/controls/assigneesSelect/assignees.helpers.ts:53]: I think it's better to keep the `notFoundName` here and rename `invalidItemName` instead

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

**Review by sanmont3drepo — APPROVED** [review]

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

File: frontend/src/v5/store/containers/containers.selectors.ts [hunk 3]
```diff
@@ -79,7 +79,7 @@ export const selectContainerUsers = createSelector(
 	selectCurrentTeamspaceUsersByIds,
 	(container, users) => {
 		if (isEmpty(users)) return [];
-		return (container?.users || []).map((user) => ({ ...user, ...users[user.user] }));
+		return (container?.users || []).map((user) => ({ ...user, ...users[user.user], isNotTeamspaceUser: !some(users, ((u) => u.user === user.user)) }));
```
Comment (sanmont3drepo) [inline frontend/src/v5/store/containers/containers.selectors.ts:82]: I dont think is necesarry to use "some" users is a dictionary
```suggestion
				return (container?.users || []).map((user) => ({ ...user, ...users[user.user], isNotTeamspaceUser: !Boolean(users[user.user])}));
```

**Review by sanmont3drepo — CHANGES_REQUESTED** [review]

**Review by Amantini1997 — APPROVED** [review]

**Review by sanmont3drepo — APPROVED** [review]
