### PR TITLE
Issue #2634 - Fixed creating normal groups with 0 meshes and refactor

### LINKED ISSUE #2634: Normal groups update can have 0 meshes
### Description
- This is happening in: both 
- This requires a hotfix to production: no

### Steps to replicate
- Open any model
- Create a normal group
- Deselect all meshes
- Update the group

### Expected Behaviour
- **Normal** groups should have the save button disabled when deselecting all meshes

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #2634 

#### Description
- Refactored the groups edition component to be have a simpler  method to determine if the form is dirty or valid
- Added the more than 0 meshes selected and normal group type as criteria to prove that the form is valid

#### Test cases
- Try to create or update a normal group to have 0 meshes selected, now the button is disabled all the time.

### CODE REVIEW

File: frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx [hunk 1]
```diff
@@ -108,82 +112,93 @@ export class GroupDetails extends React.PureComponent<IProps, IState> {
...
 		/>
 	));
 
+	public areSharedIdsChanged = (selectedNodes = [], groupObjects = []) => {
+		const toFullIdsDict = (dict, val) => {
+			val.shared_ids.forEach((e) => dict[val.account + '.' + val.model + '.' + e] = true);
+			return dict;
+		};
+
+		selectedNodes = selectedNodes.reduce(toFullIdsDict, {});
```
Comment (carmenfan) [inline frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx:137]: My worry is when the number of objects get huge (and it can be if someone has a massive federation and decided to select all the objects somehow...), this will grind to a halt.

I think we need some early rejects, like if the lengths doesn't compare (both the account/model level and the number of shared Ids within each account/model entry)

And I think we can assume the order as well (unity keep these as a list and just spit it out anyway so the order can be assumed) - so I don't think we need the reduction. It's much better to act quicker but potentially false positives than to grind to a halt every time.


This is definitely neater than what I'm proposing, but speed matters here i think!

**Review by carmenfan — CHANGES_REQUESTED** [review]

File: frontend/modules/groups/groups.sagas.ts [hunk 2]
```diff
@@ -403,12 +402,13 @@ function* unsubscribeFromChanges({ teamspace, modelId }) {
...
 function* resetToSavedSelection({ groupId }) {
-	const activeGroup = yield select(selectUnalteredActiveGroupDetails);
+	const activeGroup = yield select(selectActiveGroupDetails);
 	activeGroup.rules = (activeGroup || { rules: [] }).rules;
 
 	yield all([
-		put(GroupsActions.selectGroup(activeGroup)),
-		put(GroupsActions.setComponentState({ newGroup: activeGroup }))
+		put(GroupsActions.selectGroup(activeGroup))
+		// TODO: has to restore highlighted groups
```
[the remark this answers is not in the document]
Comment (sanmont3drepo) [reply frontend/modules/groups/groups.sagas.ts:410]: I dont know to be honest, it was a quick note after testing. Right now is not doing that in prod or dev. 
This is how it is working:

group

[the remark this answers is not in the document]
Comment (carmenfan) [reply frontend/modules/groups/groups.sagas.ts:410]: I think the refresh button should disable if you're under new group... as it's kind of meaningless.

File: frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx (hunk 1 above)
Comment (sanmont3drepo) [reply frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx]: Unfortunately we cant assume order, as it depends on the order which the meshes were selected.

Comment (carmenfan) [reply frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx]: Yea, what I mean is if the order isn't right even if the same set of mesh we just return and say something has changed, as that would only be caused by user has done some interaction with the viewer.

Comment (carmenfan) [reply frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx]: it's a false positive, but it's better than going through with the whole process... I think.

**Review by carmenfan — CHANGES_REQUESTED** [review]
- [x] Cancelling highlight shouldn't trigger the save button to be enabled if the group is a smart group - the rules were not changed:
aa

- [x] removing the rule then re-pasting it back in is causing for the save button to be enabled even though I have made no change:
aa

**Review by carmenfan — APPROVED** [review]
