### PR TITLE
ISSUE #3912 - fix username validator

### LINKED ISSUE #3912: Signup username can only start with letter or whitespace
### Description

When trying to signup a new user, the username can only start with (zero or more optional whitespaces followed by) a letter.

- This is happening in: staging
- This requires a hotfix to production: no

### Steps to replicate
- Try to signup a user in either v4 or v5

### Current Behaviour
- If the username does not start with a letter or some whitespaces followed by a letter, the field is considered invalid

### Expected Behaviour
- The username should allow underscores and number to be the first character in the username

### Pictures/ Gifs of the error
image
image

### Notes
The Regex used seems incorrect
used one: ```/^[a-zA-Z][\w]{1,65}$/```
possibly right one: ```/^[a-zA-Z0-9_]{1,65}$/```

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3912 

#### Description
The username validator has been updated to reflect the backend's one

### CODE REVIEW

File: frontend/src/v5/validation/userSchemes/validators.ts [hunk 1]
```diff
@@ -33,14 +33,14 @@ export const username = trimmedString
...
 		formatMessage({
 			id: 'userRegistration.username.error.max',
-			defaultMessage: 'Username is limited to 65 characters',
+			defaultMessage: 'Username is limited to 63 characters',
 		}))
-	.matches(/^[a-zA-Z][\w]{1,65}$/, formatMessage({
+	.matches(/^[a-zA-Z0-9_\w-]{2,63}$/, formatMessage({
 		id: 'user.username.error.characters',
-		defaultMessage: 'Username can only consist of letters, numbers and underscores',
+		defaultMessage: 'Username can only consist of letters, numbers, hypens, and underscores',
```
Comment (The-Daniel) [inline frontend/src/v5/validation/userSchemes/validators.ts:43]: typo with "hyphens"

**Review by The-Daniel — CHANGES_REQUESTED** [review]

**Review by The-Daniel — APPROVED** [review]
