### PR TITLE
Issue 4467 - Tabular View fixes

### LINKED ISSUE #4467: Tabular View - fixes
### Description
(This should be a  subbranch of #4347)
Tabular view has the major features in place, but comes with some minor issues.

### Goals
This branch should address the following:
- [ ] When a user tries to create a ticket that requires the viewer, they shouldn't get stuck;
- [ ] Properties disabled because they required the viewer should state that more clearly;
- [ ] There should be an indication about which ticket is currently being edited

### Tasks
- [ ] When a user tries to create a ticket that requires the viewer, the "go to viewer" button should be enabled;
- [ ] Properties disabled because they required the viewer should state that in the name;
- [ ] TBD

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #4467 

#### Description
Ticket properties disabled outside the viewer now have grey background and a label prefix;
When a user tries to create a ticket that requires the viewer, the "go to viewer" button is enabled;
The edited ticket (selected) now has a grey background to make it clear it is being edited

#### Test cases
Go to the tickets tab and select a template that has required properties that need the viewer:
- try to create a new ticket (button "go to viewer" should be enabled);
- try to edit an existing ticket;
   - the ticket should get a grey background
   - the uneditable properties stand out

### CODE REVIEW

File: frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx [hunk 1]
```diff
@@ -78,8 +78,9 @@ export const TicketsTable = () => {
 	const [sidePanelTicket, setSidePanelTicket] = useState<Partial<ITicket>>(null);
 	const [showCompleted, setShowCompleted] = useState(false);
 
-	const editingTicketId = sidePanelTicket?._id;
+	const selectedTicketId = sidePanelTicket?._id;
 	const templateIsFetched = templateAlreadyFetched(selectedTemplate || {} as any);
+	const isEditingValidTicket = sidePanelModelId && !selectedTicketId && !hasRequiredViewerProperties(selectedTemplate);
```
Comment (The-Daniel) [inline frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx:83]: I'm not sure I understand this. I take it it's supposed to be true if the user is editing a ticket which does not require the viewer for any properties. But the `!selectedTicketId` requirement would surely be true only when creating a new ticket? When testing this it doesn't seem to be the case which is confusing me.

Also is there any reason why the "Open in 3D Viewer" button should be disabled when creating a ticket that doesn't have viewer required properties?

File: frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketImageContent/ticketImage/ticketImage.component.tsx [hunk 2]
```diff
@@ -34,7 +35,7 @@ export const TicketImage = ({ value, onChange, onBlur, disabled: inputDisabled,
 	useEffect(() => { setTimeout(() => { onBlur?.(); }, 200); }, [value]);
 
 	return (
-		<InputContainer disabled={disabled} {...props}>
+		<ViewerInputContainer disabled={disabled} {...props}>
 			<Label>{label}</Label>
```
Comment (The-Daniel) [inline frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketImageContent/ticketImage/ticketImage.component.tsx:39]: Missing the ViewerOnlyPropertyLabel

File: frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableContent.component.tsx [hunk 3]
```diff
@@ -73,7 +76,16 @@ export const TicketsTableContent = ({ setSidePanelData }: TicketsTableContentPro
...
 	}
 
-	if (groupBy === NONE_OPTION) return (<TicketsTableGroup ticketsWithModelId={filteredItems} onNewTicket={onGroupNewTicket('')} onEditTicket={setSidePanelData} />);
+	if (groupBy === NONE_OPTION) {
+		return (
+			<TicketsTableGroup
+				ticketsWithModelId={filteredItems}
+				onNewTicket={onGroupNewTicket('')}
+				onEditTicket={setSidePanelData}
+				selectedTicketId={selectedTicketId}
```
Comment (The-Daniel) [inline frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableContent.component.tsx:85]: Would it be best to use a context instead of passing selectedTicketId down through components?

**Review by The-Daniel — CHANGES_REQUESTED** [review]

File: frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx (hunk 1 above)
Comment (Amantini1997) [reply frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx:83]: Sorry about the name, I am going to change that. It should have been `isCreatingValidTicket` or something similar.

As for the second question, that was the original design, that is, such a button disabled in new tickets and enabled for existing ones. I wonder if should keep it like that. @carmenfan

File: frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketImageContent/ticketImage/ticketImage.component.tsx [hunk 4]
```diff
@@ -34,7 +35,7 @@ export const TicketImage = ({ value, onChange, onBlur, disabled: inputDisabled,
 	useEffect(() => { setTimeout(() => { onBlur?.(); }, 200); }, [value]);
 
 	return (
-		<InputContainer disabled={disabled} {...props}>
+		<ViewerInputContainer disabled={disabled} {...props}>
```
Comment (The-Daniel) [inline frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketImageContent/ticketImage/ticketImage.component.tsx:38]: image
Should the user be able to set an image here, but not a screenshot? Or might that be too complex

File: frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx (hunk 1 above)
Comment (carmenfan) [reply frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx:83]: > As for the second question, that was the original design, that is, such a button disabled in new tickets and enabled for existing ones. I wonder if should keep it like that. @carmenfan

It makes sense as a user flow because the whole point of that button is "go to the ticket in 3D Viewer"

If you're creating a ticket then there's nothing to go to.

Comment (The-Daniel) [reply frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx:83]: It could open the viewer with the create ticket card already open

File: frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableContent.component.tsx (hunk 3 above)
Comment (Amantini1997) [reply frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableContent.component.tsx:85]: It's really just one component that does not need it (`TicketsTable`), yet receives it and passes it down to the children
Creating a context just for that one property seems an overkill tbh

File: frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx [hunk 5]
```diff
@@ -215,10 +216,10 @@ export const TicketsTable = () => {
 					</FlexContainer>
 				</FiltersContainer>
 			</FormProvider>
-			<TicketsTableContent setSidePanelData={setSidePanelData} />
+			<TicketsTableContent setSidePanelData={setSidePanelData} selectedTicketId={selectedTicketId} />
 			<SidePanel open={!!sidePanelModelId}>
 				<SlidePanelHeader>
-					<OpenInViewerButton disabled={!editingTicketId} onClick={openInViewer}>
+					<OpenInViewerButton disabled={isEditingValidTicket} onClick={openInViewer}>
```
[the remark this answers is not in the document]
Comment (Amantini1997) [reply frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx:222]: Given this https://github.com/3drepo/3drepo.io/pull/4479#discussion_r1341559901
I will mark this as resolved

File: frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketView/ticketView.component.tsx
[the remark this answers is not in the document]
Comment (Amantini1997) [reply frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketView/ticketView.component.tsx:1]: I don't have that, but there are problems related to groups. For instance, the meshes lose the colour overrides when you expand a ticket (as opposed to just select it from the tickets list) and the groups don't load 
image

This is also happening in staging and I believe the bug was introduced here https://github.com/3drepo/3drepo.io/pull/4403

I created an issue for it https://github.com/3drepo/3drepo.io/issues/4482

**Comment by The-Daniel** [comment]
I've noticed I'm still getting the ability to create a screenshot in the comments
image

**Comment by The-Daniel** [comment]
image
I've remembered another bug that you noticed during the demo. The description does not get an error state. (the submit button correctly invalidates, but there is no red outline or helpertext)

**Review by The-Daniel — CHANGES_REQUESTED** [review]
Just the two previous comments. The current code looks fine

**Review by The-Daniel — APPROVED** [review]
