### PR TITLE
Issue 1503 - Fix not working hlinks

### LINKED ISSUE #1503: Hyperlinks don't work
Hyperlinks are not highlighted and don't work across viewer UI. 

image

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #1503

### CODE REVIEW

File: frontend/routes/components/linkableField/linkableField.component.tsx [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+
+import * as React from 'react';
+
+interface IProps {
+	children: any;
+	className?: string;
+}
+
+// tslint:disable-next-line:max-line-length
+const urlRegex = /^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/;
```
Comment (carmenfan) [inline frontend/routes/components/linkableField/linkableField.component.tsx]: we should make the last one less strict, we've had problems customer emails ending in `.global`, which would go against this regex (only allowing 2-5 characters on the last bit)
