### PR TITLE
Issue 5616 - Custom Tickets - Throws an error if the user tries to impose a default property type on a complex type

### LINKED ISSUE #5616: Custom Tickets - Throws an error if the user tries to impose a default property type on a complex type
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/437

As it stands the user could impose a default value for complex types like images and viewpoints.

We don't currently support this thus it may be better to throw an error when a user is trying to create/edit a template to have such feature to manage expectations

NOTE: we should make the logic clean and easy to add more property types for unsupported defaults in the future (i.e. avoid adhoc hard coding!)

### Steps to replicate
create a template with a default viewpoint/image/imagelist

### Current Behaviour
this will pass, but the tickets created on the UI will not contain the default viewpoint.

### Expected Behaviour
this should fail and tell the user that we don't support a default in those properties

### PR DESCRIPTION
**Pull request by Bogdan-Crn**
This fixes #5616 

#### Description
Created a test that does not allow users to create or update a template with a complex type (View, Image, ImageList) that has a default value.

#### Acceptance Criteria
- [x] fails and tell the user that we don't support a default in those properties.

### CODE REVIEW

File: backend/src/v5/schemas/tickets/templates.js [hunk 1]
```diff
@@ -143,7 +149,7 @@ const propSchema = Yup.object().shape({
 
 		if (type === propTypes.ANY_OF) return res.oneOf(values);
 
-		if (type === propTypes.IMAGE || type === propTypes.IMAGE_LIST) return Yup.mixed().strip();
+		if (complexTypes.has(type)) return Yup.mixed();
```
Comment (ChristosTsiotsias) [inline backend/src/v5/schemas/tickets/templates.js]: I would put somehting like this here

```
if (complexTypes.includes(type)) {
			return Yup.mixed().test('invalid-default', `Default property cannot be applied to ${type}`, (value) => !value);
		}
```

havent tested it fully but I think this would do the trick and then you won't need the noDefaultsOnComplexTypesTest test case

File: backend/src/v5/schemas/tickets/templates.js [hunk 2]
```diff
@@ -279,6 +285,30 @@ const validTabularPropsTest = (val, context) => {
...
+	const template = TemplateSchema.generateFullSchema(val);
+
+	for (const prop of template.properties) {
+		if (propertyCheck(complexTypes, prop)) {
+			return context.createError({ message: `Property type "${prop.type}" for "${prop.name}" property does not support a default value` });
+		}
+	}
+
+	for (const mod of template.modules) {
+		// console.log(mod);
```
Comment (ChristosTsiotsias) [inline backend/src/v5/schemas/tickets/templates.js]: remove this and the one in line 302
