### PR TITLE
ISSUE #3954 - fix intercom

### LINKED ISSUE #3954: Intercom does not load
### Description
Intercom does not load correctly

- This is happening in: both
- This requires a hotfix to production: yes

### Steps to replicate
- Open the app

### Current Behaviour
- Intercom wither does not appear or it does not work

### Expected Behaviour
- Intercom should load and work correctly

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3954

#### Description
Intercom should work as usual

#### Test cases
1) Log in, refresh the page, the intercom should still be there
2) Click on the intercom, the content should load correctly

### CODE REVIEW

File: frontend/src/v5/ui/components/intercom/intercom.component.tsx [hunk 1]
```diff
@@ -41,21 +41,29 @@ const IntercomButton = () => {
...
+	}, [isAuthenticated, currentUser.email]);
 
 	return <div />;
 };
 
 export const Intercom = () => {
 	const { intercomLicense } = clientConfigService;
+
+	let appId = intercomLicense;
+	const commentStartIndex = intercomLicense.indexOf('#');
```
Comment (carmenfan) [inline frontend/src/v5/ui/components/intercom/intercom.component.tsx:58]: @Amantini1997 get rid of this hack, you should assume what's coming in is correct. It's only a problem in local (create an issue in local so @keifgwinn can deal with it)

**Review by carmenfan — CHANGES_REQUESTED** [review]

**Review by carmenfan — APPROVED** [review]
