### PR TITLE
ISSUE #5321 - Fixed position of endornament in autocomplete select boxes

### LINKED ISSUE #5321: The dropdown buttons are in the wrong position when uploading a file
### Description
The dropdown buttons are in the wrong position when uploading a file 

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- Navigate to containers or drawings
- Click on upload files

### Current Behaviour
- The destination button looks wrong 

### Expected Behaviour
- The destination button should look right

### Pictures/ Gifs of the error
image

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #5321 

#### Description
- Updated v5 theme to get of rid of problematic position: static for end ornament

### CODE REVIEW

File: frontend/src/v5/ui/themes/theme.ts [hunk 1]
```diff
@@ -520,7 +520,6 @@ export const theme = createTheme({
 				openText: '',
 				closeText: '',
 				clearText: '',
-				handleHomeEndKeys: true,
```
Comment (Amantini1997) [inline frontend/src/v5/ui/themes/theme.ts:523]: Why was this removed?

**Review by The-Daniel — APPROVED** [review]

**Review by Amantini1997 — APPROVED** [review]
