### PR TITLE
ISSUE #4248 - Fix crashes when a Federation contains an 'unassigned' container

### LINKED ISSUE #4248: Receiving 401 error when  viewing a federation where some of the containers have insufficient permissions
### Description

You get a 401 error message when you open up a federation where one or more constituent containers have 'unassigned' as the user permission.
This is occurring because there is a `fetchContainerStats` call being made (in viewer.sagas.ts). This is done for a check (in viewer.tsx) to see if all the containers have no revisions. If all the containers are empty the "Federation is empty" message gets called (in viewer.tsx).
There should be a different way of checking if the federation has no valid models to show that doesn't use `fetchContainerStats`

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Create a federation with containers A and B
- Set the permissions for a user so that they can view container A, but container B is 'unassigned'
- As that user attempt to view the federation

### Current Behaviour
- You get a 401- NOT_AUTHORIZED error and are redirected to the project page

### Expected Behaviour
- You can access the model and only see the containers you have permissions to

### Pictures/ Gifs of the error

MicrosoftTeams-image (2)

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #4248  and #4250 

#### Description
- Fixed a crash that occurred when opening a mixed permissions federation. When the containers stats are fetched only containers which the user has permissions to are used
-  Fixed a crash that occurred when editing a mixed permissions federation. Unassigned containers were showing up as 'undefined'. These are now filtered out

#### Test cases
-
    - Create a federation with containers A and B
    - Set the permissions for a user so that they can view container A, but container B is 'unassigned'
    - As that user attempt to edit the federation
    - As that user attempt to view the federation

- Opening a federation with no containers will still show the 'Add containers' screen

- Opening a federation that contains only empty containers will still show the 'Upload revisions' screen

### CODE REVIEW

**Comment by Amantini1997** [comment]
Trying to create a federation seems to not work anymore. The submit button is stuck in a loading state

**Comment by Amantini1997** [comment]
Trying to edit a federation, the submit button is always available and onSubmit the page refreshes

File: frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederation.component.tsx [hunk 1]
```diff
@@ -52,7 +53,7 @@ export const EditFederation = ({ federation, onContainersChange }: EditFederatio
 	}, [containers]);
 
 	useEffect(() => {
-		onContainersChange(includedContainers);
+		onContainersChange(pickBy(includedContainers, identity)); // filter out 'undefined' which are unassigned containers
```
Comment (Amantini1997) [inline frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederation.component.tsx:56]: `pickBy` seems to return an object rather than an array, maybe you could use `includedContainers.filter(Boolean)`?

I think this should also fix the problems I mentioned early in the main feed

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

**Comment by Amantini1997** [comment]
If I try to edit a federation that contains a container I am unassigned to, the app crashes

File: frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederation.component.tsx (hunk 1 above)
Comment (Amantini1997) [reply frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederation.component.tsx]: Should the `unassigned` container be displayed though when a collaborator is editing the federation?

**Review by Amantini1997 — APPROVED** [review]

**Review by sanmont3drepo — APPROVED** [review]
I created a separate issue to treat the edit federation modal problems #4263
