### PR TITLE
Issue 5669 - ResetProcessingFlags does not reset drawings

### LINKED ISSUE #5669: ResetProcessingFlags does not reset drawings
ResetProcessingFlags does not reset drawing statuses. This is because the drawings status are stored in the history collection instead of the model settings collection. The script needs to be updated to check drawings.history

#### Steps to reproduce
- Manually edit the drawing status to produce some unfinished revisions (i.e. produce some drawing containers to be in a processing/queued state)
- Run the resetProcessingFlags utility script

#### Current behaviour
does not reset drawing statuses

#### Expected behaviour
should reset drawing statuses

### PR DESCRIPTION
**Pull request by Bogdan-Crn**
This fixes #5669 

#### Description
Updated the resetProcessingFlags script to include drawings as well. Drawings will be set as failed status in the database rather than the status being unset.
Updated the tests to include drawings and added an extra test to check for drawings only.

#### Acceptance Criteria

- [ ] when the script is run any drawings that have a status as queued will be set as failed

### CODE REVIEW

File: backend/src/scripts/utility/modelProcessing/resetProcessingFlags.js [hunk 1]
```diff
@@ -30,15 +30,20 @@ const { v5Path } = require('../../../interop');
...
+	const modelQuery = model ? { _id: model } : {};
+	const drawingQuery = model ? { model } : {};
 
-	const action = { $unset: { status: 1 } };
-	await updateMany(teamspace, SETTINGS_COL, query, action);
+	const modelAction = { $unset: { status: 1 } };
+	await updateMany(teamspace, SETTINGS_COL, modelQuery, modelAction);
+
+	const drawingAction = { $set: { status: 'failed' } };
+	await updateMany(teamspace, DRAWINGS_HISTORY_COL, { ...drawingQuery, status: 'queued' }, drawingAction);
```
Comment (ChristosTsiotsias) [inline backend/src/scripts/utility/modelProcessing/resetProcessingFlags.js]: it also needs to update the ones that are 'processing'

File: backend/tests/v5/scripts/modelProcessing/resetProcessingFlags.test.js [hunk 2]
```diff
@@ -82,32 +119,52 @@ const runTest = () => {
...
+		});
+
+		test('Should only process the predefined drawing if it is defined', async () => {
+			const lastInd = data[0].models.length - 1;
+			await ResetProcessingFlags.run(data[0].teamspace, data[0].drawings[lastInd]);
+			await Promise.all([
+				...data.map(
+					({ teamspace, models, drawings }, ind) => checkModelsStatus(
+						teamspace,
+						ind === 0 ? models.slice(0, -1) : models,
```
Comment (ChristosTsiotsias) [inline backend/tests/v5/scripts/modelProcessing/resetProcessingFlags.test.js]: just pass models

File: backend/tests/v5/scripts/modelProcessing/resetProcessingFlags.test.js [hunk 3]
```diff
@@ -82,32 +119,52 @@ const runTest = () => {
...
+						ind === 0 ? drawings.slice(0, -1) : drawings,
+						false,
+					),
+				),
+				checkModelsStatus(data[0].teamspace, [data[0].models[lastInd]], [], true),
+			]);
+		});
+
+		test('Should only process the predefined drawing if it is defined', async () => {
+			const lastInd = data[0].models.length - 1;
```
Comment (ChristosTsiotsias) [inline backend/tests/v5/scripts/modelProcessing/resetProcessingFlags.test.js]: data[0].drawings.length*

File: backend/tests/v5/scripts/modelProcessing/resetProcessingFlags.test.js [hunk 4]
```diff
@@ -42,19 +48,46 @@ const setupData = () => {
...
-
-	expect(data.length).toBe(expectedData.length);
-	expect(data).toEqual(expect.arrayContaining(expectedData));
+const checkModelsStatus = async (teamspace, models, drawings, expectReset, index) => {
+	const modelsData = await findModels(teamspace, { _id: { $in: models } }, { _id: 1, status: 1 });
+
+	const expectedModelsData = models.map((_id, ind) => ({ _id, status: expectReset ? undefined : modelStates[ind] }));
+
+	const drawingsData = await Promise.all(
+		drawings.map((_id) => getRevisionByIdOrTag(
```
[the remark this answers is not in the document]
Comment (Bogdan-Crn) [reply backend/tests/v5/scripts/modelProcessing/resetProcessingFlags.test.js]: the reason for not calling Revisions.getRevisions is because it does not include failed and I wanted to ensure that the status did change to failed

**Review by carmenfan — APPROVED** [review]
