### PR TITLE
Issue 4580 - hot fix for groups issues

### LINKED ISSUE #4580: Custom tickets groups: editing does not work
### Description
Editing a custom ticket groups does not fill the data correctly in the panel

- This is happening in: both
- This requires a hotfix to production: yes

### Steps to replicate
- Create a custom ticket with a default view and proceed to create 2 groups
- Refresh
- Try to edit one of the 2 groups

### Current Behaviour
- The panel is either not being filled with the data when the "edit" button is clicked the first time, or it's not populated at all

### Expected Behaviour
- The panel should be populated after the first click

### Pictures/ Gifs of the error

https://github.com/3drepo/3drepo.io/assets/43547703/76caa253-a42d-415a-9e3e-ba07fd20f997

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #4580 

#### Description
- Fixes edition of groups in tickets
- Creation of new groups in new tickets

#### Test cases

**1**
- Create a custom ticket with a default view and proceed to create 2 groups
- Refresh
- Try to edit one of the 2 groups
- The panel should be populated after the first click

**2**
- Click on  new ticket with a template with a viewpoint
- Without saving the new ticket create a group
- Edit the group
- The form should have the correct group data

**3**
- Click on  new ticket with a template with a viewpoint
- Without saving the new ticket create a group
- Try to create another group
- Both groups should appear and be editable

### CODE REVIEW

**Comment by Amantini1997** [comment]
Wrong colour applied to groups:
- Open the new ticket form and before saving the ticket, open the groups list;
- Click on "create group" in the coloured section;
- Without closing the panel, click on "create group" in the hidden section;

### Current behaviour
The colour that was selected for the coloured group is applied to the hidden group

### Expected behaviour
The new hidden group should be colourless

(Note: the opposite is also true)

Uploading Registrazione 2023-11-10 144139.mp4…

**Comment by sanmont3drepo** [comment]
> Wrong colour applied to groups:
> 
> * Open the new ticket form and before saving the ticket, open the groups list;
> * Click on "create group" in the coloured section;
> * Without closing the panel, click on "create group" in the hidden section;
> 
> ### Current behaviour
> The colour that was selected for the coloured group is applied to the hidden group
> 
> ### Expected behaviour
> The new hidden group should be colourless
> 
> (Note: the opposite is also true)
> 
>  Registrazione.2023-11-10.144139.mp4

fixed

**Comment by sanmont3drepo** [comment]
> Wrong colour applied to groups:
> 
> * Open the new ticket form and before saving the ticket, open the groups list;
> * Click on "create group" in the coloured section;
> * Without closing the panel, click on "create group" in the hidden section;
> 
> ### Current behaviour
> The colour that was selected for the coloured group is applied to the hidden group
> 
> ### Expected behaviour
> The new hidden group should be colourless
> 
> (Note: the opposite is also true)
> 
>  Registrazione.2023-11-10.144139.mp4

fixed

File: frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx [hunk 1]
```diff
@@ -132,7 +132,7 @@ export const GroupSettingsForm = ({ value, onSubmit, onCancel, prefixes, isColor
 			newValues.group.objects = meshObjectsToV5GroupNode(data);
 		}
 
-		if (!newValues.color) {
+		if (!isColored) {
```
Comment (Amantini1997) [inline frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx:135]: This creates an error when the user selects the no-color option (the one with a red diagonal line)

File: frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx [hunk 2]
```diff
@@ -100,7 +100,9 @@ export const TicketGroups = ({ value, onChange, onBlur }: TicketGroupsProps) =>
 	};
 
 	// If there is no  group it gets a key to get identified within the groups array
-	const onSetEditGroup = (type) => (index) => setEditingOverride({ override: cloneDeep(settingsFormGroups?.[index]) || { key: count++ }, type });
+	const onSetEditGroup = (type) => (index) => {
+		setEditingOverride({ override: cloneDeep(state?.[type]?.[index]), type, editing:true });
```
Comment (Amantini1997) [inline frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx:104]: This is not a change request, but in the future, could we rename "editingOverride" to something else, like sidePanelOverride? It is confusing to have a flag property "editing" for something called "editingOverride"

**Review by carmenfan — APPROVED** [review]

**Review by carmenfan — CHANGES_REQUESTED** [review]
#### Hide button doesn't seem to work in the group list
I have the roof hidden in this ticket: https://issue-4580.dev.3drepo.io/v5/viewer/DevTeamWorkspace/7b6c7bd0-054a-11ee-ac5b-59e952832776/0aed56a0-2d3f-11ee-8c0b-17a4bf167a31?ticketId=ba3523e9-19fc-425c-b8d4-8c3bb0e51ed6

Bit of I've unhide it on the group list, I can't seem to hide it again. I think it's to do with it being selected. Maybe it should auto unselect if the hide button is triggered?
img-13-54-23-11-54

**Comment by carmenfan** [comment]
Wrong icon when we have partial toggle : 
image

**Comment by Amantini1997** [comment]
##### Update group creates a new group
- Go to the viewer and refresh the page;
- Click on new ticket (select a template with groups)
- Create a new group;
- Edit the group.

##### Expected behvaiour
The ticket should update

##### Actual behaviour
A new ticket is created

https://github.com/3drepo/3drepo.io/assets/43547703/1a62d8c4-1113-4b1c-bec0-691ba7154840

**Comment by Amantini1997** [comment]
##### Deleting a group being edited does not close the side panel
When an existing group is being edited, and (before saving the edit) deleted, the the side panel stays open

https://github.com/3drepo/3drepo.io/assets/43547703/7b91fd98-c3a8-496e-928d-25c201ab4834

**Comment by sanmont3drepo** [comment]
> ##### Update group creates a new group
> * Go to the viewer and refresh the page;
> * Click on new ticket (select a template with groups)
> * Create a new group;
> * Edit the group.
> 
> ##### Expected behvaiour
> The ticket should update
> 
> ##### Actual behaviour
> A new ticket is created
> 
>  Registrazione.2023-11-13.120611.mp4

Fixed

**Review by Amantini1997 — APPROVED** [review]

**Review by carmenfan — APPROVED** [review]
