### PR TITLE
ISSUE #5195 - Bugs with Drag and Drop area "drag over" state

### LINKED ISSUE #5195: Uploading files - Bugs with Drag and Drop area "drag over" state
### Description
Product issue:  https://github.com/3drepo/3D-Repo-Product-Team/issues/462

1 - The Drag and Drop component incorrectly loses its teal 'active' state if the user drags a file over the text inside the Drag and Drop component. This is purely visual and dropping the file still works as expected
2 - If the user were to (for some reason) drag a selection of text over the area and let go then the component gets stuck in the active state

- This is happening in: prod/staging/**both** 
- This requires a hotfix to production: yes/**no** 

### Steps to replicate
- Open the file uploads modal

1)
- Drag a file over the Drag and Drop are
- Drag the file over the text/button

2)
- Select some of the text in the modal
- Drag it over the Drag and Drop area and let go

### Current Behaviour
- The drag and drop shows the incorrect state

### Expected Behaviour
- The state of the drag and drop component reflects accurately whether a file is being held over it

### Pictures/ Gifs of the error
image

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #5195

#### Description
Updated react-dropzone.
Changed component to use hooks and isDragActive which fixes the two bugs

#### Test cases

- The drag and drop works fully
- Dragging and dropping text into the area has no effect
- When dragging a file into the zone the state does not become disabled when dragging over text/buttons inside the component

### CODE REVIEW

File: frontend/src/v5/ui/controls/dragAndDrop/dragAndDrop.component.tsx [hunk 1]
```diff
@@ -15,43 +15,22 @@
...
-
-	const handleDragLeave = () => {
-		setDragOverlay(false);
-	};
-
-	const handleDrop = (files) => {
-		onDrop(files);
-		setDragOverlay(false);
-	};
+export const DragAndDrop = ({ children, onDrop, ...props }: IDragAndDrop) => {
```
Comment (Amantini1997) [inline frontend/src/v5/ui/controls/dragAndDrop/dragAndDrop.component.tsx:27]: In staging, dropping a file with an invalid (not supported) extension on the container revision upload modal does nothing. Now, instead, it creates a new revision entry
image

File: frontend/src/v5/ui/controls/dragAndDrop/dragAndDrop.component.tsx [hunk 2]
```diff
@@ -15,43 +15,22 @@
  *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  */
 
-import { useState } from 'react';
-import { Container, DashedContainer, DropArea } from './dragAndDrop.styles';
+import { DashedContainer, DropArea } from './dragAndDrop.styles';
+import { useDropzone } from 'react-dropzone';
 
 interface IDragAndDrop {
-	hidden?: boolean;
```
Comment (Amantini1997) [inline frontend/src/v5/ui/controls/dragAndDrop/dragAndDrop.component.tsx:22]: This was used to hide the dragAndDrop container. If you want to remove it, you may need to adjust the components that were passing it (I can only think of of ticket comments creation and after uploading a new revision file, but there may be others)

e.g. container revision upload after uploading:

staging (after uploading)
image


now (after uploading)
image

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

**Review by Amantini1997 — DISMISSED** [review]

**Review by sanmont3drepo — DISMISSED** [review]

**Review by sanmont3drepo — APPROVED** [review]
