### PR TITLE
ISSUE #5896 - Upgrade to react 19: Fix upload containers/drawings ui

### LINKED ISSUE #5896: Upgrade to react 19: Fix upload containers/drawings ui
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/942
 upload containers/drawings ui is broken

### Goals
- Have nice ui for uploading containers
- Have nice ui for uploading drawings

### Tasks
- [ ] Fix uploads UI

### Related Resources

Image

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #5896
#### Description
The drawings upload modal was broken in that when you selected a destination it did not actually set the drawing name, drawingId, and other related values in the form. As a result when you opened the sidebar it was blank and the form would never validate

Also fixed some console errors/warnings

### CODE REVIEW

File: frontend/src/v5/ui/components/shared/uploadFiles/uploadFiles.component.tsx [hunk 1]
```diff
@@ -72,7 +72,7 @@ export const UploadFiles = ({
 			isValid={isValid}
 			contrastColorHeader
 			fields={fields}
-			isUploading={isUploading}
+			isuploading={isUploading}
```
Comment (sanmont3drepo) [inline frontend/src/v5/ui/components/shared/uploadFiles/uploadFiles.component.tsx:75]: why the name change?

**Review by sanmont3drepo — CHANGES_REQUESTED** [review]

File: frontend/src/v5/ui/components/shared/uploadFiles/uploadFiles.component.tsx (hunk 1 above)
Comment (The-Daniel) [reply frontend/src/v5/ui/components/shared/uploadFiles/uploadFiles.component.tsx:75]: To silence this console warning

Image

**Review by sanmont3drepo — APPROVED** [review]
