### PR TITLE
ISSUE #1706 - Fix darkscrollbars when they are not needed in dashboard

### LINKED ISSUE #1706: Windows 10 screen zoom bug
### Description
Under certain conditions there is a a black scrollbar showing in the dashboard.

### Steps to replicate
- In windows 10  set scale to 150 and display resolution to 1920x1080
image
- hover over the dashboard

### Pictures/ Gifs of the error
image

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #1706

### CODE REVIEW

File: frontend/routes/teamspaces/teamspaces.component.tsx [hunk 1]
```diff
@@ -467,19 +468,13 @@ export class Teamspaces extends React.PureComponent<IProps, IState> {
...
-								<Loader content="Loading teamspaces..." />
-							</LoaderContainer>
-						) : (
-							<SimpleBar>
-								{this.renderTeamspaces(this.props.teamspaces)}
-							</SimpleBar>
-						)
-					}
-				</List>
+				<BodyWrapper>
```
Comment (carmenfan) [inline frontend/routes/teamspaces/teamspaces.component.tsx]: This change (I think) has made the loading screen disappear.
(left is staging right is this branch)
ham
