### PR TITLE
Issue 1798 - Issues/risks bugs

### LINKED ISSUE #1798: Issue bugs
- **Filtering by issue date doesn't seems to give you correct results:**
My list:
image
If I filter for anything from 30th Oct:
image

- **The issue list needs to go back to the right place when the user exit an issue that is closed.**
At the moment the issue list goes back to the right place (kind of) if you exit an issue:
markup
But if I closed the issue and exit, it goes back up to the top:
markup

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #1798

### CODE REVIEW

File: frontend/routes/viewerGui/components/reportedItems/reportedItems.component.tsx [hunk 1]
```diff
@@ -200,6 +202,7 @@ export class ReportedItems extends React.PureComponent<IProps, IState> {
 		const showDefaultHiddenItemsChanged = prevProps.showDefaultHiddenItems !== showDefaultHiddenItems;
 		const searchEnabledChange = prevProps.searchEnabled !== searchEnabled;
 		const detailsWasClosed = prevProps.showDetails !== showDetails && !showDetails;
+		const detailsShowing =  prevProps.showDetails !== showDetails && showDetails;
```
Comment (carmenfan) [inline frontend/routes/viewerGui/components/reportedItems/reportedItems.component.tsx]: Doesn't look like this is used anywhere? @sanmont3drepo

Comment (sanmont3drepo) [reply frontend/routes/viewerGui/components/reportedItems/reportedItems.component.tsx]: Yes, sorry, was a previous attempt.
