### PR TITLE
ISSUE #5392 - Fixed white screen when loading tickets from deprecated templates

### LINKED ISSUE #5392: Tickets of deprecated templates are causing a whitescreen
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/654

- This is happening in: both
- This requires a hotfix to production: no

### Steps to replicate
- create a ticket with a template
- deprecate the template
- go view the ticket in the viewer

### Current Behaviour
viewer whitescreens

### Expected Behaviour
- Viewer should not whitescreen
- Ticket of a deprecated template can be viewed and updated
- New tickets cannot be created for this deprecated template

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #5392

#### Description
- Modified template api to use showDeprecated param
- Modified calls to fetch templates to get deprecated
- Removed 'new ticket' buttons from tabular ticket view when the selected template is a deprecated one
- Removed deprecated templates from the new drop down in tickets card

#### Test cases
- Create a ticket with a template
- Deprecate the template
- Refresh (the page shouldnt white screen)
- Try creating a ticket with a  deprecated template in ticket cards and tabular view (shouldnt be possible)

### CODE REVIEW

**Comment by The-Daniel** [comment]
This doesn't seem to be working for me. I still get a whitescreen when I try to open a federation containing this deprecated template:

```javascript
{
  "modules": [],
  "deprecated": "true",
  "properties": [
    {
      "type": "text",
      "required": true,
      "name": "Baz"
    }
  ],
  "config": {
    "pin": true,
    "defaultImage": true,
    "issueProperties": true
  },
  "code": "FOO",
  "name": "Foo Bar"
}
```

**Review by The-Daniel — CHANGES_REQUESTED** [review]
This doesn't seem to be working for me. I still get a whitescreen when I try to open a federation containing this deprecated template:

```javascript
{
  "modules": [],
  "deprecated": "true",
  "properties": [
    {
      "type": "text",
      "required": true,
      "name": "Baz"
    }
  ],
  "config": {
    "pin": true,
    "defaultImage": true,
    "issueProperties": true
  },
  "code": "FOO",
  "name": "Foo Bar"
}
```

**Review by The-Daniel — APPROVED** [review]

File: frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableGroup/ticketsTableGroup.component.tsx [hunk 1]
```diff
@@ -126,6 +131,7 @@ export const TicketsTableGroup = ({ tickets, onEditTicket, onNewTicket, selected
 										selected={selectedTicketId === ticket._id}
 									/>
 								))}
+								{!template.deprecated &&
```
Comment (Amantini1997) [inline frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableGroup/ticketsTableGroup.component.tsx:134]: I was looking at a template from the tabular view, then I set that same template to "deprecated", and refreshed. The app crashes with this error:
image

As such, I think this is not necessary as a deprecated template is not reacheable, but we may need a way to handle invalid templates passed in the URL

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

File: frontend/src/v5/services/api/tickets.ts [hunk 2]
```diff
@@ -24,8 +24,19 @@ export const fetchContainerTemplates = async (
 	projectId: string,
 	containerId: string,
 	getDetails?: boolean,
+	showDeprecated?: boolean,
 ): Promise<FetchTemplatesResponse> => {
-	const { data } = await api.get(`teamspaces/${teamspace}/projects/${projectId}/containers/${containerId}/tickets/templates?getDetails=${getDetails}`);
+	const urlSearchParams = new URLSearchParams();
+
+	if (getDetails) {
+		urlSearchParams.set('getDetails', getDetails.toString());
```
[the remark this answers is not in the document]
Comment (sanmont3drepo) [reply frontend/src/v5/services/api/tickets.ts:32]: I think it only receives string. and if getDetails is a boolean it throws an error.

File: frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableGroup/ticketsTableGroup.component.tsx (hunk 1 above)
Comment (sanmont3drepo) [reply frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableGroup/ticketsTableGroup.component.tsx:134]: Cant reproduce this with a deprecated template. Yes with an  invalid templatem but that is out of scope.

**Review by Amantini1997 — APPROVED** [review]
