### PR TITLE
ISSUE #4308 - Now in tickets is sending a timestamp when the date fields are changed

### LINKED ISSUE #4308: Dates in custom tickets  are being updated/created using the wrong format
### Description
In  custom tickets when a date property is being updated  a string is being sent instead of a number

- This is happening in: both 
- This requires a hotfix to production: no

### Steps to replicate
- Open the developers tools
- Update a date property of a custom ticket 

### Current Behaviour
- It sends a string

### Expected Behaviour
- It should send a timestamp

### Pictures/ Gifs of the error
image

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #4308

#### Description
- Changed due date to use timestamp
- Changed date property fields to use timestamp
- Should sent a timestamp instead of a string for dates

#### Test cases
- update a due date (in existing and a new ticket)
- update a due date in the details ticket view  (in existing and a new ticket)
- update another type of date in the details ticket view  (in existing and a new ticket)

### CODE REVIEW

File: frontend/src/v5/ui/controls/dueDate/baseDueDate.component.tsx [hunk 1]
```diff
@@ -38,17 +39,18 @@ export const BaseDueDate = ({ value: initialValue, disabled, onBlur, ...props }:
 		if (!open) setOpen(!disabled);
 	};
 	const onDateChange = (newValue) => {
+		const timestamp = !newValue ? null : newValue.toDate().getTime();
```
Comment (The-Daniel) [inline frontend/src/v5/ui/controls/dueDate/baseDueDate.component.tsx:42]: I find the use of '!' here unusual, but I don't care too much

**Review by The-Daniel — DISMISSED** [review]

File: frontend/src/v5/ui/controls/dueDate/baseDueDate.component.tsx (hunk 1 above)
Comment (sanmont3drepo) [reply frontend/src/v5/ui/controls/dueDate/baseDueDate.component.tsx:42]: Maybe thiw would be better?
```suggestion
		const timestamp = newValue?.toDate()?.getTime() || null;
```

**Review by The-Daniel — APPROVED** [review]
