### PR TITLE
ISSUE #5130 - Milestone 1: Fixed format of drawing status in drawings list

### LINKED ISSUE #5130: [2D MVP] Milestone 1: Bad format in drawing status in drawings list
### Description
Product issue:  https://github.com/3drepo/3D-Repo-Product-Team/issues/377.

### Bugs

- [ ] The status of the model is being  tagged at the end of the revision name 
image

How it should look
image

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #5130

#### Description
- Fixed the format of the drawing status
- Made the LatestRevision component reusable between containers and drawings
- Renamed the enum UploadStatus which was being used for containers to ContainersUploadStatus so as to avoid confusion with drawings uploads

#### Test cases
- Navigate to the drawings list
- Test uploads with different statuses

#### Notes
- One way of easily viewing the upload status without the upload competing is to pause the bouncer from docker. Any uploads will have the status `Queued`

### CODE REVIEW

**Review by sanmont3drepo — APPROVED** [review]

File: frontend/src/v5/ui/components/shared/latestRevision/latestRevision.component.tsx [hunk 1]
```diff
@@ -17,34 +17,27 @@
...
 interface ILatestRevision extends IRevisionStatus {
 	hasRevisions: boolean;
+	emptyLabel: string;
 }
 
-export const LatestRevision = ({ hasRevisions, status, ...props }: ILatestRevision): JSX.Element => (
+export const LatestRevision = ({ hasRevisions, status, emptyLabel, ...props }: ILatestRevision): JSX.Element => (
 	<Container disabled={!hasRevisions}>
-		{hasRevisions || status !== UploadStatus.OK ? (
+		{hasRevisions || status !== ContainerUploadStatus.OK ? (
```
Comment (Amantini1997) [inline frontend/src/v5/ui/components/shared/latestRevision/latestRevision.component.tsx:31]: I was thinking about the separation introduced for UploadStatus with "DrawingUploadStatus" and "ContainerUploadStatus". As there as some components shared between drawings and containers, they shouldn't have any specific knowledge about either, but some, like this one, do. For instance, here you checking the value of the status against `ContainerUploadStatus` which is no longer the same as for drawings

**Review by sanmont3drepo — APPROVED** [review]

**Review by Amantini1997 — APPROVED** [review]
