### PR TITLE
Issue 3523 - Fix dropdown menu in Viewer Compare card

### LINKED ISSUE #3523: Compare Card dropdown menus look messed up
### Description
The elements in the list of `Compare` card include a dropdown. This dropdown doesn't not seem to work correctly

- This is happening in: staging
- This requires a hotfix to production: no

### Steps to replicate
- Open a container in the viewer;
- Go to `Compare` (**1st bug**)
- Click on the dropdown menu (**2nd bug**)

### Current Behaviour
- **1st bug:**  the dropdown looks weird;
- **2nd bug:** the dropdown looks even worse, and the label on the left shift up and hides a bit

### Expected Behaviour
- the dropdown should not move and should not hide under the title;
- the label on the left of the dropdown should not move;

### Pictures/ Gifs of the error
**unselected revision**
image

**selected revision**
image

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3523

#### Description
Fixed compare card dropdown menu

#### Test cases
Open the viewer with a federation, go to compare cards, test the select input

### CODE REVIEW

File: frontend/src/v5/ui/themes/theme.ts [hunk 1]
```diff
@@ -847,24 +856,34 @@ export const theme = createTheme({
...
+			defaultProps: {
+				shrink: false,
+			},
 			styleOverrides: {
 				root: {
 					position: 'absolute',
 					...typography.body1,
 					fontSize: '12px',
+					top: '-35.5px',
+					left: '-13px',
```
Comment (The-Daniel) [inline frontend/src/v5/ui/themes/theme.ts:868]: image
This causes problems in the Smart groups settings

File: frontend/src/v5/ui/controls/formSelect/formSelect.component.tsx [hunk 2]
```diff
@@ -14,12 +14,13 @@
...
  */
-import { FormControl, SelectProps } from '@mui/material';
+import { FormControl, SelectProps, InputLabel } from '@mui/material';
 import { Controller } from 'react-hook-form';
-import { Select, InputLabel } from './formSelect.styles';
+import { Select } from './formSelect.styles';
 
 export type FormSelectProps = SelectProps & {
 	control: any;
+	name: string;
```
Comment (sanmont3drepo) [inline frontend/src/v5/ui/controls/formSelect/formSelect.component.tsx:23]: This is not necessary the name is already part of SelectProps unless I guess you want to make it not optional. If we didnt have problems with forgetting that dont change it.

File: frontend/src/v5/ui/routes/viewer/theme.ts [hunk 3]
```diff
@@ -100,13 +100,25 @@ export const theme = createTheme(
...
+					},
+				},
 				MuiTextField: {
 					styleOverrides: {
 						root: {
 							margin: 0,
 							'& .MuiInputBase-root input': {
 								lineHeight: 22,
-								height: 24,
+								height: 26,
```
Comment (The-Daniel) [inline frontend/src/v5/ui/routes/viewer/theme.ts:116]: This line causes text to be cut off in the Links list when adding attachments
image

File: frontend/src/v5/ui/controls/formSelect/formSelect.component.tsx [hunk 4]
```diff
@@ -44,6 +46,7 @@ export const FormSelect = ({
 		<Controller
 			control={control}
 			name={name}
+			defaultValue={defaultValue}
```
Comment (sanmont3drepo) [inline frontend/src/v5/ui/controls/formSelect/formSelect.component.tsx:49]: what happens if defaultValue is undefined?

**Review by The-Daniel — CHANGES_REQUESTED** [review]

**Review by sanmont3drepo — CHANGES_REQUESTED** [review]

File: frontend/src/v5/ui/v4Adapter/overrides/cards/compare.overrides.ts [hunk 5]
```diff
@@ -0,0 +1,33 @@
+/**
+ *  Copyright (C) 2022 3D Repo Ltd
+ *
+ *  This program is free software: you can redistribute it and/or modify
```
[the remark this answers is not in the document]
Comment (Amantini1997) [reply frontend/src/v5/ui/v4Adapter/overrides/cards/compare.overrides.ts:4]: This one is a known bug and it is to be addressed in another issue that is already open https://github.com/3drepo/3drepo.io/issues/3442

File: frontend/src/v5/ui/controls/formSelect/formSelect.component.tsx (hunk 4 above)
Comment (Amantini1997) [reply frontend/src/v5/ui/controls/formSelect/formSelect.component.tsx:49]: the input switches from 'uncontrolled' to 'control' as soon as it changes its value printing an error in the console

File: frontend/src/v5/ui/controls/formSelect/formSelect.component.tsx (hunk 2 above)
Comment (Amantini1997) [reply frontend/src/v5/ui/controls/formSelect/formSelect.component.tsx:23]: Indeed it is because of that. In the creation of the form multiselect component, I forgot to pass the name and I was getting a non-exhaustive error. 
image
Since the name is required by the controller that wraps up the MUI select component, name is no longer optional. 
But I can revert this if you want

File: frontend/src/v5/ui/routes/viewer/theme.ts [hunk 6]
```diff
@@ -118,7 +130,7 @@ export const theme = createTheme(
 							lineHeight: '22px',
 							height: '24px',
 							padding: '0 10px',
-							marginTop: '18px',
+							marginTop: 0,
```
[the remark this answers is not in the document]
Comment (Amantini1997) [reply frontend/src/v5/ui/routes/viewer/theme.ts:133]: When I feel stressed or something bad happens to me during the weekend, that's my way of relaxing and easing my mind 😄

**Review by The-Daniel — APPROVED** [review]

**Review by sanmont3drepo — APPROVED** [review]
