### PR TITLE
ISSUE #5179 - Performance improvement in drawings upload form

### LINKED ISSUE #5179: Drawing upload modal gets very laggy if you have multiple drawings
The revision code input box gets really slow when:

- you upload multiple files
- drawing container is filled in

Notice on the screenshot how the revision code input box was still relatively repsonsive, but once i've filled in the other fields it gets quite laggy:

#### Steps to reproduce
- try to upload many drawings
- fill in drawing destinatino and status code
- try to type in a revision code

#### Current behaviour
Input box is very laggy - input is coming up much slower than when the characters were typed

#### Expected behaviour
Should be responsive.

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #5179

#### Description
- Improves performance in drawings upload form

#### Test cases
- upload +10 drawings at the same time and trigger errors by for example setting an already existing status+rev code combination in the drawing's revisions.

### CODE REVIEW

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

File: frontend/src/v5/store/drawings/drawings.selectors.ts [hunk 1]
```diff
@@ -32,6 +32,15 @@ import { Calibration } from './drawings.types';
 
 const selectDrawingsDomain = (state): DrawingsState => state?.drawings || ({ drawingsByProjectByProject: {} });
 
+const selectRawDrawingById =  createSelector(
+	selectDrawingsDomain,
+	selectCurrentProject,
+	(_, id: string) => id,
+	(state, currentProject, id) =>
+		(state.drawingsByProject[currentProject] ?? []).find((drawing) => drawing._id === id) || {},
```
Comment (Amantini1997) [inline frontend/src/v5/store/drawings/drawings.selectors.ts:40]: The first part of `selectRawDrawingById` and `selectDrawings` is duplicated code and could be extracted into a new selector like `selectCurrentProjectDrawings` or `selectDrawingsByProject`
image
<details>
  <summary>Refactored code (you can copy paste)</summary>
  
  ```ts
const selectDrawingsByProject = createSelector(
	selectDrawingsDomain,
	selectCurrentProject,
	(state, currentProject) => state.drawingsByProject[currentProject] ?? [],
);

const selectRawDrawingById =  createSelector(
	selectDrawingsByProject,
	(_, id: string) => id,
	(drawings, id) => drawings.find((drawing) => drawing._id === id) || {},
);

export const selectDrawings = createSelector(
	selectDrawingsByProject,
	selectRevisionsByDrawing, // This selector is used here to recalculate the value after the revisions are fetched
	(drawings) => orderBy(drawings.map(fullDrawing), 'lastUpdated', 'desc'),
);

export const selectDrawingById = createSelector(
	selectDrawings,
	(_, _id) => _id,
	(drawings, _id) => drawings.find((d) => d._id === _id),
);
```

</details>

File: frontend/src/v5/store/drawings/drawings.selectors.ts [hunk 2]
```diff
@@ -32,6 +32,15 @@ import { Calibration } from './drawings.types';
```
Comment (Amantini1997) [inline frontend/src/v5/store/drawings/drawings.selectors.ts:32]: Uploading to a specific drawing does not populate the destination field (although it does show the drawing as being used)


Uploading Registrazione 2024-11-18 112435.mp4…

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

File: frontend/src/v5/ui/routes/dashboard/projects/drawings/uploadDrawingRevisionForm/uploadList/uploadListItem/uploadListItem.component.tsx [hunk 3]
```diff
@@ -170,16 +170,27 @@ export const UploadListItem = ({
...
+			{/* <UploadListItemDestination 
+				name={`${revisionPrefix}.drawingName`}
+				key={`${uploadId}.dest`}
+				onSelectNewDestination={onClickEdit}
+				index={index}
+				revisionPrefix={revisionPrefix}
+				disabled={disabled}
+				error={!!drawingNameError}
+				helperText={drawingNameError}
+			/> */}
```
Comment (Amantini1997) [inline frontend/src/v5/ui/routes/dashboard/projects/drawings/uploadDrawingRevisionForm/uploadList/uploadListItem/uploadListItem.component.tsx:193]: This can be deleted

File: frontend/src/v5/ui/routes/dashboard/projects/drawings/uploadDrawingRevisionForm/uploadList/uploadListItem/uploadListItem.component.tsx [hunk 4]
```diff
@@ -170,16 +170,27 @@ export const UploadListItem = ({
...
 			<InputController
```
Comment (Amantini1997) [inline frontend/src/v5/ui/routes/dashboard/projects/drawings/uploadDrawingRevisionForm/uploadList/uploadListItem/uploadListItem.component.tsx:194]: Upload a revision to a specific drawing and then try to clear the destination. It will crash the app
image

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

**Review by Amantini1997 — APPROVED** [review]

File: frontend/src/v5/ui/routes/dashboard/projects/drawings/uploadDrawingRevisionForm/uploadList/uploadListItem/components/uploadListItemStatusCode/uploadListItemStatusCode.component.tsx [hunk 5]
```diff
@@ -63,7 +63,6 @@ export const UploadListItemStatusCode = ({ value, inputRef, onChange, helperText
 				/>
 			)}
 			ListboxComponent={OptionsBox}
-			disableClearable={!value}
```
Comment (Amantini1997) [inline frontend/src/v5/ui/routes/dashboard/projects/drawings/uploadDrawingRevisionForm/uploadList/uploadListItem/components/uploadListItemStatusCode/uploadListItemStatusCode.component.tsx:66]: When the preset drawing gets cleared, the "clearable" button persists


https://github.com/user-attachments/assets/07554506-30c1-4702-9429-7cbde4a01e9b

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

**Review by Amantini1997 — APPROVED** [review]
