### PR TITLE
ISSUE #4405 - Bugs related to navigating from a model in one teamspace/project directly to another

### LINKED ISSUE #4045: Need to update the action that talks to Azure DevOps
### Description
<html>
<body>

Call Azure Destroy PipelineNode.js 12 actions are deprecated. Please update the following actions to use Node.js 16: Azure/pipelines@v1.2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
--
Call Azure Destroy PipelineThe `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

</body>
</html>

```
[Call Azure Destroy Pipeline](https://github.com/3drepo/3drepo.io/actions/runs/4323367286/jobs/7546894011)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: Azure/pipelines@v1.2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
[Call Azure Destroy Pipeline](https://github.com/3drepo/3drepo.io/actions/runs/4323367286/jobs/7546894011#step:2:11)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### Suggested solution

- [ ] update action to latest, if it fixes it, and submit pull request and fix it if it's not.

### LINKED ISSUE #4405: Error when opening federation's ticket after notifications panel navigation
### Description
Whilst in a model if you use the notifications panel to navigate to a federation in a different teamspace and then attempt to open a ticket. You will get an error and be redirected to the original teamspace.

The error seems to be that the app thinks the model is a container so sends the ticket and template fetches to the incorrect endpoint

Possibly linked to #4404 

NOTE: This issue might need to wait for PR https://github.com/3drepo/3drepo.io/pull/4403 since this appears to fix ISSUE https://github.com/3drepo/3drepo.io/issues/4402 which can cause a crash before this happens

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- Open a model in the viewer
- Open the notifications panel and use it to open a model in another teamspace
- Try to view a ticket

### Current Behaviour
- A warning modal appears and redirects you to the original teamspace

### Expected Behaviour
- There is no error, and you can view the ticket

### Pictures/ Gifs of the error
image
image
Api request to containers endpoint when it is a federation

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #4405 and #4404

#### Description
When using the notifications sidebar to open a model in a different teamspace or project the redux states for currentTeamspace, currentProject, and projects in the new teamspace were not updated/fetched.
This caused some 404 issues that would redirect you from the viewer. e.g. trying to open a ticket
This also caused the breadcrumbs to appear incorrectly

#### Test cases
Open a model and use the notifications sidebar to navigate to models in other teamspaces or projects. Check that the breadcrumbs are correct and see if anything in the viewer is broken

### CODE REVIEW

File: frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx [hunk 1]
```diff
@@ -90,18 +90,20 @@ export const TicketDetailsCard = () => {
...
 	useEffect(() => {
-		if (!templateAlreadyFetched(template)) {
-			TicketsActionsDispatchers.fetchTemplate(
-				teamspace,
-				project,
-				containerOrFederation,
-				template._id,
-				isFederation,
-			);
+		if (ticket?._id) {
```
Comment (Amantini1997) [inline frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx:93]: To make it more concise, can you make this if a return statement if the condition is false?
Like this
```ts
if (!ticket?.id) return;

if (!templateAlreadyFetched(template) {
   ...
```

File: frontend/src/v5/ui/routes/viewer/viewer.tsx [hunk 2]
```diff
@@ -56,6 +56,15 @@ export const Viewer = () => {
 		return () => ViewerService.off(VIEWER_EVENTS.CLICK_PIN, handlePinClick);
 	}, [tickets]);
 
+	useEffect(() => {
+		TeamspacesActionsDispatchers.setCurrentTeamspace(teamspace);
+	}, [teamspace]);
+
+	useEffect(() => {
+		ProjectsActionsDispatchers.setCurrentProject(project);
+		ProjectsActionsDispatchers.fetch(teamspace);
```
Comment (Amantini1997) [inline frontend/src/v5/ui/routes/viewer/viewer.tsx:65]: shouldn't this go in the useEffect above?
Afterall you want to fetch the projects when the teamspace changes as opposed to when the project does.

Also, dashboardViewerLayout does something similar, but it does it only once (note the dependencies list is empty). Could it be that replacing its useEffect code with what you have here is enough?

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

**Comment by Amantini1997** [comment]
There appear to be some bugs when you navigate across different revisions using the notifications
For instance, if I start from an empty model and I get to a valid one, I get a couple of errors.
Also, the "empty model" overlay component doesn't get unmounted

Uploading Registrazione 2023-10-12 095856.mp4…

**Comment by Amantini1997** [comment]
From a valid revision (revision A), navigate to an empty federation using the notifications, then try to reach any other valid revisions (even just navigating backward). An error modal keeps popping up and it becomes impossible to navigate away from the current revision

(P.s. refresh the page when you are in the Revision A, just to make sure)

https://github.com/3drepo/3drepo.io/assets/43547703/5d0efa92-41c9-4bb9-886b-4e52626d7d6c

File: frontend/src/v4/services/viewer/viewer.tsx [hunk 3]
```diff
@@ -753,7 +753,11 @@ export class ViewerService {
 	}
 
 	public async isViewerReady() {
-		return await (this.initialisedPromise && this.initialisedPromise.promise);
+		try {
+			return await this.initialisedPromise.promise;
+		} catch {
+			console.error('Error occurred when checking Viewer readiness')
```
Comment (Amantini1997) [inline frontend/src/v4/services/viewer/viewer.tsx:759]: Is it possible to trace what causes the error and fix it there instead of logging an error message?

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

File: frontend/src/v4/services/viewer/viewer.tsx (hunk 3 above)
Comment (sanmont3drepo) [reply frontend/src/v4/services/viewer/viewer.tsx:759]: lets get of this try. initialization problems will be addressed in #4576 4576

File: frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx [hunk 4]
```diff
@@ -128,7 +129,7 @@ export const TicketDetailsCard = () => {
 		setTicketId();
 		TicketsCardActionsDispatchers.setCardView(TicketsCardViews.List);
 	}, []);
-
+	if (!ticket) return null;
```
Comment (sanmont3drepo) [inline frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx:132]: Why is this file is changed?

**Review by sanmont3drepo — CHANGES_REQUESTED** [review]

File: frontend/src/v4/services/viewer/viewer.tsx (hunk 3 above)
Comment (sanmont3drepo) [reply frontend/src/v4/services/viewer/viewer.tsx:759]: will be addressed in #4576

File: frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx (hunk 4 above)
Comment (The-Daniel) [reply frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx:132]: There was a crash when navigating backwards to a model with a ticket open in a different project. The tickets card opens before the ticket is defined

**Review by sanmont3drepo — DISMISSED** [review]

File: frontend/src/v4/modules/viewerGui/viewerGui.sagas.ts [hunk 5]
```diff
@@ -401,17 +401,20 @@ function* loadModel() {
...
 
 	} catch (error) {
-		const content = 'The model was either not found, failed to load correctly ' +
-			'or you are not authorized to view it. ' +
-			' You will now be redirected to the teamspace page.';
-		yield put(DialogActions.showDialog({ title: 'Model Error', content }));
-
 		if (v5) {
 			if (matchPath(location.pathname, { path: ROUTES.V5_MODEL_VIEWER })) {
+				const content = 'The model was either not found, failed to load correctly ' +
```
Comment (Amantini1997) [inline frontend/src/v4/modules/viewerGui/viewerGui.sagas.ts:406]: As this is in v5, should we format it?

File: frontend/src/v4/modules/viewerGui/viewerGui.sagas.ts [hunk 6]
```diff
@@ -401,17 +401,20 @@ function* loadModel() {
...
+					'or you are not authorized to view it. ' +
+					' You will now be redirected to the previous page.';
+				yield put(DialogActions.showDialog({ title: 'Model Error', content }));
```
Comment (Amantini1997) [inline frontend/src/v4/modules/viewerGui/viewerGui.sagas.ts:409]: Same here about formatting

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

**Review by Amantini1997 — APPROVED** [review]
