### PR TITLE
ISSUE #3154 - fix broken revisions

### LINKED ISSUE #3154: Revisions dialog crash
### Description
When you open the revisions dialog of a model the app goes blank
- This is happening in: staging
-
### Steps to replicate
- Open a model in the viewer with multiple revisions
- open the revisions dialogs

### Current Behaviour
- Page goes blank

### Expected Behaviour
- A dialog with the revisions list should be opened

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3154 

#### Description
Fixed revision dialog crashing app on open

### CODE REVIEW

File: frontend/src/v4/routes/components/revisionsListItem/revisionsListItem.component.tsx [hunk 1]
```diff
@@ -65,8 +65,8 @@ export const RevisionsListItem = (props: IProps) => {
 
 	const handleClick = (event) => props.onClick(event, props.data);
 	const handleToggleVoid = (event) => props.onToggleVoid(event, props.data);
-	const themeProps = useMemo(() =>
-		({ current, void: props.data.void, isPending }), [isPending, props.data.void, current]
+	const stateTheme = useMemo(() =>
+		({ current, isVoid: props.data.void, isPending }), [isPending, props.data.void, current]
 	);
```
Comment (sanmont3drepo) [inline frontend/src/v4/routes/components/revisionsListItem/revisionsListItem.component.tsx:70]: we can get rid of this and just pass the props to the container instead of using a memo, unless there is a good reason for using it.

Comment (Amantini1997) [reply frontend/src/v4/routes/components/revisionsListItem/revisionsListItem.component.tsx:70]: useMemo has been removed

**Review by sanmont3drepo — APPROVED** [review]
