### PR TITLE
ISSUE #4748 -Fix crash when editing groups in new ticket

### LINKED ISSUE #4748: Entering groups in a new ticket crashes the app
### Description
When creating a new ticket if you try to add a group without saving first it crashes the app

- This is happening in: prod
- requires a hotfix to production: yes/no @carmenfan ?

### Steps to replicate
- Create a ticket  from a with a default view
- Without saving the new ticket enter groups

### Current Behaviour
- The app crashes

### Expected Behaviour
- Groups should be able to be created without problems

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #4748 

#### Description
- Rollback to how ticket groups worked.
- Added isEditting group to avoid clashes when editing the group and showing the viewpoint.

#### Test cases
- Creating a new ticket and editing the groups in the moment should work

**No regression bugs:**
- Selecting a ticket in the list should show the view, closing and opening the ticket card should not reset the view.
- Editing groups should work as expected

### CODE REVIEW

File: frontend/src/v4/routes/viewerGui/viewerGui.component.tsx [hunk 1]
```diff
@@ -73,6 +73,7 @@ interface IProps {
 	selectedTicket: ITicket | undefined;
 	treeNodesList: any;
 	ticketsCardView: TicketsCardViews;
+	isEditingGroups: boolean;
```
Comment (Amantini1997) [inline frontend/src/v4/routes/viewerGui/viewerGui.component.tsx:76]: I can't see any component using this

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

File: frontend/src/v4/routes/viewerGui/viewerGui.component.tsx (hunk 1 above)
Comment (sanmont3drepo) [reply frontend/src/v4/routes/viewerGui/viewerGui.component.tsx:76]: in line 192

Comment (Amantini1997) [reply frontend/src/v4/routes/viewerGui/viewerGui.component.tsx:76]: Oh, right, my bad.

In that case, I saw that the `view` object that you get from Ticket context is either `Form` or `Groups`; but:

- Using `TicketsCardHooksSelectors.selectView()` is possible to determine if you are looking at the `Form` (if the value is not `List`, it's either the new ticket or the details of an existing one, so the form view).
- With the new `isEditingGroups` is also possible to determine if the form is group mode, equivalent to `Groups` from ticketContext.

As such, do we still need to keep the `view` in ticketContext?

Comment (sanmont3drepo) [reply frontend/src/v4/routes/viewerGui/viewerGui.component.tsx:76]: Yes. If you take a look the PR undoes that idea because that approach makes it prone to errors. Because the ticketview property is agnostic to wether is a new ticket or you are updating an existing ticket, it is better that navigation (switching between groups and no groups) is also agnostic. Otherwise it has to know if you are going from a new ticket or an already existing one. Bottom line, that is an idea that already failed.

File: frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx [hunk 2]
```diff
@@ -197,7 +197,12 @@ export const TicketGroups = ({ value, onChange, onBlur }: TicketGroupsProps) =>
 		dispatch(ViewpointsActions.clearColorOverrides());
 
 		ViewerService.on(VIEWER_EVENTS.BACKGROUND_SELECTED, clearHighlightedIndex);
-		return () => ViewerService.off(VIEWER_EVENTS.BACKGROUND_SELECTED, clearHighlightedIndex);
+
+		TicketsCardActionsDispatchers.setEditingGroups(true);
+		return () => {
+			ViewerService.off(VIEWER_EVENTS.BACKGROUND_SELECTED, clearHighlightedIndex);
+			TicketsCardActionsDispatchers.setEditingGroups(false);
```
[the remark this answers is not in the document]
Comment (sanmont3drepo) [reply frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx:204]: If it is a whitescreen that appears in this branch and not in prod then I should fix it.

File: frontend/src/v4/routes/viewerGui/viewerGui.component.tsx (hunk 1 above)
Comment (The-Daniel) [reply frontend/src/v4/routes/viewerGui/viewerGui.component.tsx:76]: I'll create a ticket for the pin bug

**Review by Amantini1997 — APPROVED** [review]

File: frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (sanmont3drepo) [reply frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx:204]: Fixed the crash, but the original bug still remains.

File: frontend/src/v5/ui/routes/viewer/tickets/ticket.context.tsx [hunk 3]
```diff
@@ -23,22 +23,22 @@ export enum TicketDetailsView {
...
+	detailsView: TicketDetailsView;
+	detailsViewProps?: any;
 	setDetailViewAndProps: (view: TicketDetailsView, props?: any) => void;
 }
 
 const defaultValue: TicketContextType = {
 	isViewer: false,
-	view: TicketDetailsView.Form,
+	detailsView: TicketDetailsView.Form,
 	setDetailViewAndProps: () => {},
```
Comment (The-Daniel) [inline frontend/src/v5/ui/routes/viewer/tickets/ticket.context.tsx:34]: Sorry. One last thing. Should this not be `setDetailsViewAndProps` instead of `setDetailViewAndProps`

**Review by carmenfan — APPROVED** [review]

File: frontend/src/v5/ui/routes/viewer/tickets/ticket.context.tsx (hunk 3 above)
Comment (sanmont3drepo) [reply frontend/src/v5/ui/routes/viewer/tickets/ticket.context.tsx:34]: there are two fields that are set by that function `detailsView` and `detailsViewProps`

Comment (The-Daniel) [reply frontend/src/v5/ui/routes/viewer/tickets/ticket.context.tsx:34]: Yes, so why is it detail and not details in this case?

Comment (sanmont3drepo) [reply frontend/src/v5/ui/routes/viewer/tickets/ticket.context.tsx:34]: Ahh ok. cool. I'll rename that in another PR, is not worth to get another round of reviews just for an s.

**Review by The-Daniel — APPROVED** [review]
