### PR TITLE
ISSUE #5890 - Upgrade to react 19: Fix users tab

### LINKED ISSUE #5890: Upgrade to react 19: Fix users tab
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/942
Users tab goes blank (check if its fixed in ISSUE_5588

### Goals
- Users tab should be working

### Tasks
- [ ]  Fix Users tab

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #5890

#### Description
Prevented the crash when opening this tab in the same way as was done with the jobs tab.

Fixed several styling issues that resulted from upgrade to react 19

### CODE REVIEW

File: frontend/src/v4/routes/components/invitationDialog/invitationDialog.component.tsx [hunk 1]
```diff
@@ -132,54 +132,58 @@ export const InvitationDialog = (props: IProps) => {
...
-										control={
-											<Checkbox
-												checked={field.value}
-												{...field}
-												onChange={handleProjectAdminChange(field, form, index)}
-												color="secondary"
-											/>
-										}
-										label="Project Admin"
+				{projects.map(({ project, isAdmin }, index) => {
```
Comment (sanmont3drepo) [inline frontend/src/v4/routes/components/invitationDialog/invitationDialog.component.tsx:135]: I dont know if its already broken in staging, but clicking invite seems to do nothing for me.

https://github.com/user-attachments/assets/43c8dc2d-bab3-4cd1-b898-1a19a0109c0e

**Review by sanmont3drepo — CHANGES_REQUESTED** [review]

File: frontend/src/v4/routes/users/users.component.tsx [hunk 2]
```diff
@@ -21,14 +21,14 @@ import {
...
 	isEqual,
-	isNumber,
 	matches,
 	pick,
 	pickBy,
 	values
 } from 'lodash';
-import ReactDOM from 'react-dom';
 
+import { FormattedMessage } from 'react-intl';
```
Comment (sanmont3drepo) [inline frontend/src/v4/routes/users/users.component.tsx:30]: ### Description
Add a new user that is not registered is not working correctly

### Steps to replicate
1. Click on the "⨁ Add user" button.
2. Enter an email that is not registered to 3D Repo.
3. Assign any one of the job.
4. Click on "+ Add user" button.

### Current Behaviour
- It closes the new user form

https://github.com/user-attachments/assets/61d2f0f7-3b54-4a57-875e-1506458dcd11


### Expected Behaviour
- To show a 'User not found.Send invitation?' message
Image

**Review by sanmont3drepo — CHANGES_REQUESTED** [review]

File: frontend/src/v4/routes/components/newUserForm/newUserForm.component.tsx [hunk 3]
```diff
@@ -240,14 +241,14 @@ export class NewUserForm extends PureComponent<IProps, IState> {
...
-					{this.renderUserNotFoundMessage(this.state.userNotExists)}
+					{this.renderUserNotFoundMessage(this.props.userNotExists)}
 					<Grid
 						container
 						direction="row">
 						<SaveButton
 							variant="contained"
 							color="secondary"
-							disabled={this.state.userNotExists || !this.state.name || !this.state.job || this.state.job.length === 0}
+							disabled={this.props.userNotExists || !this.state.name || !this.state.job || this.state.job.length === 0}
```
Comment (sanmont3drepo) [inline frontend/src/v4/routes/components/newUserForm/newUserForm.component.tsx]: The state of usernotexists is now permanent

https://github.com/user-attachments/assets/ed3322cd-d27c-43a0-b013-ebce6efb4f3c

**Review by sanmont3drepo — CHANGES_REQUESTED** [review]

**Review by sanmont3drepo — APPROVED** [review]
