### PR TITLE
ISSUE #5348 - Fixed bad default value for colorpicker

### LINKED ISSUE #5348: Viewer white screens when trying to create a group in tickets
### Description
Viewer white screens when trying to create a group in tickets
error-blank

### Reproducible steps
- Open the tickets card
- Click on a  ticket that supports groups
- Click on add new group
- Click on coloured groups
- Click on Add group

### Current behaviour
White screens

### Expected behaviour
Shows the groups UI

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #5348 

#### Description
- Support new error codes

#### Test cases
- Add a new coloured group to a ticket

### CODE REVIEW

File: frontend/src/v5/ui/controls/inputs/colorPicker/colorPicker.component.tsx [hunk 1]
```diff
@@ -15,15 +15,15 @@
...
 import ChevronIcon from '@assets/icons/outlined/thin_chevron-outlined.svg';
-import { defaults, isNumber } from 'lodash';
 import { ActionMenu } from '@controls/actionMenu';
 import { Container } from './colorPicker.styles';
 import { ColorPickerPalette } from './colorPickerPalette/colorPickerPalette.component';
 import { UNSET_RGB_COLOR } from './colorPicker.helpers';
 import { ColorCircle } from './colorCircle/colorCircle.styles';
-import { HexGroupColor, hexGroupColorToRgb, RgbGroupColor, rgbGroupColorToHex } from '@/v5/helpers/colors.helper';
+import { hexGroupColorToRgb, RgbGroupColor, rgbGroupColorToHex } from '@/v5/helpers/colors.helper';
+import { defaults } from 'lodash';
```
Comment (Amantini1997) [inline frontend/src/v5/ui/controls/inputs/colorPicker/colorPicker.component.tsx:26]: When I click on the colour picker inside "edit/create group", it crashes

https://github.com/user-attachments/assets/a01db3c3-c590-42b9-b1a7-79ef7d441675

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

**Review by Amantini1997 — DISMISSED** [review]

**Review by Amantini1997 — APPROVED** [review]
